### ISSUE TITLE
Doesn't work with HTTPS

### ISSUE THREAD

**Issue by jacobludriks** [liuxiong332/node-viewpoint#1]
```
_http_client.js:75
    throw new Error('Protocol "' + protocol + '" not supported. ' +
          ^
Error: Protocol "https:" not supported. Expected "http:".
    at new ClientRequest (_http_client.js:75:11)
    at HttpRequest.sendRequest (C:\scripts\ewscal\node_modules\viewpoint\node_modules\http-ext\dist\lib\http-request.js:263:30)
    at new HttpRequest (C:\scripts\ewscal\node_modules\viewpoint\node_modules\http-ext\dist\lib\http-request.js:257:10)
    at HttpRequestPool.module.exports.HttpRequestPool.newRequest (C:\scripts\ewscal\node_modules\viewpoint\dist\http\http-request-pool.js:46:14)
    at HttpRequestPool.module.exports.request (C:\scripts\ewscal\node_modules\viewpoint\dist\http\http-request-pool.js:7
6:12)
    at HttpRequestPool.module.exports.HttpRequestPool.post (C:\scripts\ewscal\node_modules\viewpoint\dist\http\http-request-pool.js:86:20)
    at EWSWebService.module.exports.RequestClient.send (C:\scripts\ewscal\node_modules\viewpoint\dist\http\request-client.js:53:29)
    at EWSWebService.module.exports.EWSWebService.doSoapRequest (C:\scripts\ewscal\node_modules\viewpoint\dist\ews-web-service.js:48:17)
    at EWSWebService.module.exports.EWSItemOperations.findItem (C:\scripts\ewscal\node_modules\viewpoint\dist\ews\ews-item-operations.js:39:17)
    at EWSClient.module.exports.ItemAccessor.findItems (C:\scripts\ewscal\node_modules\viewpoint\dist\item-accessor.js:42:21)
```

Using HTTPS for the EWS URL breaks the code.

**Comment by liuxiong332** [comment]
In version 0.1.x, I only test with Node 0.12, so this error may come from the difference of `http` module between node 0.10 and node 0.12.

@jacobludriks You can try version 0.2 that I update right now. It seems this version is OK.
